---
- hosts: 192.168.79.128
  tasks: 
    - name: Create docker/wordpress directory
      file:
        path: /opt/docker/wordpress
        state: directory
        owner: root
        group: root
        mode: 0755
    - name: Create docker-compose file
      template:
            src: docker-compose.yml.j2
            dest: /opt/docker/wordpress/docker-compose.yml
            owner: root
            group: root
            mode: 0644
    - name: Run docker-compose up -d
      shell: docker-compose up -d
      args:
        chdir: /opt/docker/wordpress/
